#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 22 11:11:20 2019

@author: apple
"""

# package used to execute HTTP POST request to the API
import requests

# API endpoint
API = "https://api.sec-api.io"

# define the filter parameters you want to send to the API 
payload = {
  "query": { "query_string": { "query": "cik:320193 AND filedAt:{2016-01-01 TO 2016-12-31} AND formType:\"10-Q\"" } },
  "from": "0",
  "size": "10",
  "sort": [{ "filedAt": { "order": "desc" } }]
}

# send the request to the API and retrieve all matching filings
r = requests.post(API, data=payload)

# store filings
text=r.text
